### ISSUE TITLE
As an ECH extension?

### ISSUE THREAD

**Issue by sayrer** [davidben/tls-key-share-prediction#2]
One thing that occurred to me is that there are use cases that could require ECH, so it could be better to include this key-share-prediction in the ECHConfig in that case?

https://www.ietf.org/archive/id/draft-ietf-tls-esni-17.html#name-configuration-extensions

Wouldn't that help the concerns about authenticity of DNS data in the draft's current SVCB?

**Comment by davidben** [comment]
I don't see how this would help. An ECHConfig is no more authentic than anything else you get over DNS, and tying this to ECH doesn't make a whole lot of sense. (If you have multiple ECHConfigs in a single SVCB, they'd all have the same information.)

**Comment by sayrer** [comment]
If someone downgraded the hint in the ECHConfig, and the server requires ECH, wouldn't the handshake fail due to this step? https://www.ietf.org/archive/id/draft-ietf-tls-esni-17.html#section-6.1-5

**Comment by davidben** [comment]
Then the server will handshake with the public name and we'd have much the same problem. Unless the outer ClientHello uses different key shares, but that defeats the point of doing a prediction.

I also do not think it makes sense to tie this to ECH. The authenticity concerns are already resolved by fixing the negotiation algorithm, which is getting done in 8446bis. And resolving the authenticity concern does not remove the need to fix the negotiation algorithm because there are non-attacker-influenced problems here.

**Comment by sayrer** [comment]
I see, you're right as of the current ECH draft: `Otherwise, if all candidate ECHConfig values fail to decrypt the extension, the client-facing server MUST ignore the extension and proceed with the connection using ClientHelloOuter`

I'm not sure the draft should require the server to proceed with the connection here, but that's for ECH.

**Comment by davidben** [comment]
ECH is undeployable without that step. It's how the recovery flow works. Removing it would also break our ability to do GREASE.

**Comment by sayrer** [comment]
Oh, I'm not against that flow at all. I think you could get the same effect by sending no `retry_configs`* and refusing non-ECH ClientHello messages, though.

Also, I didn't mean to suggest this way /instead/ of what you have now. It just seemed like a better way if the server is going to require ECH.

* (`If the server provided "retry_configs"`, Section [6.1.6](https://www.ietf.org/archive/id/draft-ietf-tls-esni-17.html#section-6.1.6))

**Comment by davidben** [comment]
> Oh, I'm not against that flow at all. I think you could get the same effect by sending no retry_configs* and refusing non-ECH ClientHello messages, though.

In order to get that far, and authenticate the retry configs, we need the server to handshake with the public name, i.e. use the outer ClientHello.

It's also a bit late to be doing such a fundamental change to ECH.

> Also, I didn't mean to suggest this way /instead/ of what you have now. It just seemed like a better way if the server is going to require ECH.

I'm not very positive on defining two different redundant mechanisms, when one already fully handles the cases we care about. :-p
